
/**
 * Represents a user's problem statement.
 */
export interface ProblemStatement {
  /** The text content of the problem statement. */
  text: string;
  /** The timestamp when the problem was stated. */
  timestamp: number;
}

/**
 * Defines the visual layout of a framework on the canvas.
 * - 'linear': Steps arranged sequentially.
 * - 'matrix_2x2': Four quadrants.
 * - 'six_hats': Special layout for Six Thinking Hats.
 */
export type FrameworkLayout = 'linear' | 'matrix_2x2' | 'six_hats';

/**
 * Represents a problem-solving framework or mental model.
 */
export interface Framework {
  /** Unique identifier for the framework. */
  id: string;
  /** Display name of the framework. */
  name: string;
  /** Category the framework belongs to. */
  category: 'Technical' | 'Product' | 'Mental Model' | 'Strategic' | 'Scientific';
  /** Brief description of the framework. */
  description: string;
  /** Explanation of why this framework is relevant to the problem. */
  relevance: string;
  /** List of steps or sections in the framework. */
  steps: string[];
  /** Visual layout type for the framework. */
  layout: FrameworkLayout;
}

/**
 * Represents a chat message in the system.
 */
export interface Message {
  /** The sender of the message. */
  role: 'user' | 'model';
  /** The content of the message. */
  content: string;
  /** The timestamp of the message. */
  timestamp: number;
}

/**
 * Enum defining the possible views or pages in the application.
 */
export enum AppView {
  LOGIN = 'LOGIN',
  HOME = 'HOME',
  FRAMEWORK_SELECTION = 'FRAMEWORK_SELECTION',
  WORKSPACE = 'WORKSPACE',
  METHODOLOGY = 'METHODOLOGY',
  METHODOLOGY_DETAIL = 'METHODOLOGY_DETAIL',
  ABOUT = 'ABOUT',
  HISTORY = 'HISTORY',
  ADMIN = 'ADMIN',
}

/**
 * Supported colors for sticky notes.
 */
export type NoteColor = 'yellow' | 'blue' | 'green' | 'pink' | 'orange' | 'white';

/**
 * Represents a single sticky note on the canvas.
 */
export interface CanvasNote {
  /** Unique identifier for the note. */
  id: string;
  /** Text content of the note. */
  content: string;
  /** Background color of the note. */
  color: NoteColor;
  /** Indicates if the note was generated by AI. */
  isAiGenerated?: boolean;
}

/**
 * Represents a section (e.g., a column or quadrant) on the canvas.
 */
export interface CanvasSection {
  /** Unique identifier for the section. */
  id: string;
  /** Title of the section (e.g., "Strengths"). */
  title: string;
  /** Contextual guidance or question for this specific problem and section. */
  description: string;
  /** List of notes contained in this section. */
  notes: CanvasNote[];
}

/**
 * Represents a saved template for a section.
 */
export interface SectionTemplate {
  /** Unique identifier for the template. */
  id: string;
  /** User-defined name for the template. */
  name: string;
  /** Creation timestamp. */
  createdAt: number;
  /** The data content of the template. */
  data: {
    title: string;
    description: string;
    notes: { content: string; color: NoteColor }[];
  };
}

/**
 * Defines the state of the canvas viewport.
 */
export interface Viewport {
  /** X-coordinate offset. */
  x: number;
  /** Y-coordinate offset. */
  y: number;
  /** Zoom scale level. */
  scale: number;
}

/**
 * Represents a saved user session.
 */
export interface SavedSession {
  /** Unique identifier for the session. */
  id: string;
  /** The problem statement associated with the session. */
  problem: ProblemStatement;
  /** The framework used in the session. */
  framework: Framework;
  /** The state of the sections on the canvas. */
  sections: CanvasSection[];
  /** The state of the viewport. */
  viewport?: Viewport;
  /** Timestamp of last modification. */
  lastModified: number;
}

/**
 * Represents a user in the system.
 */
export interface User {
  /** Unique identifier for the user. */
  id: string;
  /** Display name of the user. */
  name: string;
  /** Email address of the user. */
  email: string;
  /** Indicates if the user has admin privileges. */
  isAdmin?: boolean;
}

/**
 * Represents the state of the workspace.
 */
export interface WorkspaceState {
  /** List of sections in the workspace. */
  sections: CanvasSection[];
  /** Current zoom scale. */
  scale: number;
}
